/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/shared/Alert.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    DialogDelete: typeof import('./src/components/shared/dialogs/DialogDelete.vue')['default']
    DialogTaskField: typeof import('./src/components/shared/dialogs/DialogTaskField.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ListTasks: typeof import('./src/components/ListTasks.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToDoList: typeof import('./src/components/ToDoList.vue')['default']
  }
}
